version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile.api
    image: rw:api
    environment:
      DATABASE_URL: sqlite://./dev.db
  web:
    build:
      context: ./
      dockerfile: docker/Dockerfile.web
    image: rw:web
    ports:
      - 3000:3000
  prerender:
    build:
      context: ./
      dockerfile: docker/Dockerfile.prerender
    image: rw:prerender
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nginx
  #   image: rw:nginx
  #   ports:
  #     - 3000:3000
