FROM node:16-alpine

WORKDIR /app

COPY docker/prerender.js .

RUN apk add --no-cache ca-certificates && \
    apk add chromium --no-cache && \
    npm install prerender@5.16.1  && \
    rm -rf /var/cache/apk/*

EXPOSE 3000

CMD [ "node", "prerender.js"]
